name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK using Buildozer (Docker)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/app \
            -w /home/user/app \
            kivy/buildozer:latest \
            buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: QuizApp-APK
          path: bin/*.apk
